Ext.define("AlliBilli.view.main.center.left.RightAccordianView", {
    extend: "Ext.panel.Panel",
    xtype: "layout-accordion",
    title: "Entertainment",
    region: "east",
    id: "east-panel",
    floatable: false,
    iconCls: "fas fa-guitar",
    margin: "0 0 0 0",
    width: 250,
    minWidth: 250,
    maxWidth: 350,
    requires: ["Ext.layout.container.Accordion"],
    layout: "accordion",
    cls: Ext.baseCSSPrefix + "shadow",
    collapsible: true,
    animCollapse: true,
    margins: "0 0 0 5",
    activeOnTop: true,
  });