Ext.define("AlliBilli.view.main.center.left.LeftAccordianView", {
  extend: "Ext.panel.Panel",
  xtype: "layout-accordion",
  title: "News",
  region: "west",
  id: "west-panel",
  floatable: false,
  iconCls: "fas fa-paper-plane",
  margin: "0 0 0 0",
  width: 250,
  minWidth: 250,
  maxWidth: 350,
  requires: ["Ext.layout.container.Accordion"],
  layout: "accordion",
  cls: Ext.baseCSSPrefix + "shadow",
  collapsible: true,
  animCollapse: true,
  margins: "0 0 0 5",
  activeOnTop: true,
});